version: 0.0
os: linux
files:
  - source: example.zip
    destination: /home/ec2-user/

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user
