version: 0.0
os: linux
files:
  - source: /home/ec2-user/example.tar.gz
    destination: /home/ec2-user/
    overwrite: yes

hooks:
  ApplicationStart:
    - location: /home/ec2-user/scripts/start_server.sh
      timeout: 300
      runas: ec2-user
