name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: build/libs/

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: List build/libs contents
        run: ls build/libs

      - name: Archive build artifacts as ZIP
        run: |
          JAR_NAME=$(ls build/libs | grep '.jar$')
          echo "Found JAR file: $JAR_NAME"
          zip -r example.zip build/libs/$JAR_NAME appspec.yml scripts/
          ls -lh example.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp example.zip s3://groom-runner-bucket/example/example.zip

      - name: Check S3 upload
        run: |
          aws s3 ls s3://groom-runner-bucket/example/
          if [ $? -ne 0 ]; then
            echo "S3 upload failed or file not found in S3"
            exit 1
          else
            echo "S3 upload succeeded"
          fi

      - name: Deploy with AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name codedeploy \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name deploy-group \
            --s3-location bucket=groom-runner-bucket,bundleType=zip,key=example/example.zip
